# Generated by Django 5.2.4 on 2025-07-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("customer", "Customer"), ("vendor", "Vendor")],
                default="customer",
                max_length=10,
            ),
        ),
    ]
