# Generated by Django 5.2.4 on 2025-08-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_company_name_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("vendor", "Vendor"),
                    ("admin", "Admin"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
