# Generated by Django 5.2.4 on 2025-07-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_product_vendor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitems",
            old_name="price",
            new_name="total",
        ),
    ]
